root: true

env:
  node: true

extends:
  - 'airbnb-base'
  - 'plugin:jest/recommended'

rules:
  import/extensions: 0
  no-underscore-dangle: [2, { "allow": ["__filename", "__dirname"] }]
