 env:
    browser: true
    es2021: true
  extends:
  - airbnb-base
  parserOptions:
    ecmaFeatures:
      jsx: true
    ecmaVersion: 12
    sourceType: module
  rules:
    quotes:
      - error
      - single
    semi:
      - error
      - always
